## 1 Pandas 데이터 구조

- Pandas에서 제공하는 데이터 구조는 Series와 DataFrame이 있음

### 1.1 Series

- 각 값에 `라벨(인덱스)`이 있고 `하나의 데이터 형식`으로 이루어진 `1차원 배열`
- `라벨`로 데이터에 접근 할 수 있음

### 1.2 DataFrame

- 행과 열에 라벨이 있는 2차원 배열 ☞ Excel
- 각 `열`은 `서로 다른 데이터 타입`을 지닐 수 있음

<p align="center"><img src="https://github.com/sigirace/page-images/blob/main/kang_lectures/python_preprocessing/s_p.png?raw=true" width="600" height="300"></p>

***

## 2 DataFrame 기본

Pandas의 DataFrame을 사용하여 분석하기 위한 가장 첫 단계는 데이터를 `호출`하고 데이터의 내용과 `요약`, `통계정보`를 확인하는 것입니다. 데이터나 분석 도구에 따라 컬럼명이나 컬럼의 타입을 변경해야 할 때도 있습니다.

### 2.1 Pandas 사용 준비

🧑‍💻: olist 구매 기록 데이터를 chat gpt에 업로드 해주세요!

🔗 **실습 데이터**

- 💾 [olist 구매기록 데이터](https://github.com/sigirace/gpt_ada/blob/main/data/olist_order_dataset_practice.csv)

💬 **Chat Prompt**

> 제시한 데이터는 이커머스회사 olist의 구매기록 데이터이다. 이 데이터의 컬럼을 살펴보고 설명해라. 모든 과정에서 설명시 한국어를 사용하라.

🤖 **GPT 출력: message**

```
이 데이터는 이커머스 회사인 Olist의 구매 기록을 포함하고 있으며, 총 9개의 컬럼으로 구성되어 있습니다. 각 컬럼의 설명은 다음과 같습니다:

1. order_id: 주문 ID로, 각 주문을 고유하게 식별할 수 있는 문자열입니다.
2. customer_id: 고객 ID로, 주문을 한 고객을 고유하게 식별할 수 있는 문자열입니다.
3. order_status: 주문 상태를 나타내는 컬럼으로, ‘delivered’(배송 완료)와 같은 상태 정보가 포함됩니다.
4. order_purchase_timestamp: 주문이 이루어진 시점을 나타내는 타임스탬프로, 주문이 생성된 날짜와 시간이 기록되어 있습니다.
5. product_category: 구매된 상품의 카테고리를 나타내는 문자열입니다.
6. payment_method: 결제 수단을 나타내는 컬럼으로, ‘credit_card’(신용카드), ‘boleto’(브라질의 지불 수단) 등이 포함됩니다.
7. installments: 할부 횟수를 나타내는 컬럼으로, 고객이 구매할 때 선택한 할부 개수입니다. 일부 값은 결측치(NaN)로 표시됩니다.
8. item_price_usd: 상품의 가격을 미국 달러(USD)로 나타내는 컬럼입니다.
9. shipping_cost_usd: 배송비를 미국 달러(USD)로 나타내는 컬럼입니다.

이 데이터는 997개의 레코드(행)로 구성되어 있으며, 각 컬럼의 데이터 타입은 문자열(object)과 부동 소수점(float64)으로 구성되어 있습니다. 결측치는 installments, item_price_usd, shipping_cost_usd 컬럼에서 발견됩니다.
```

🤖 **GPT 출력:Code**

In [1]:
import pandas as pd

# 데이터 로드
file_path = 'https://raw.githubusercontent.com/sigirace/gpt_ada/main/data/olist_order_dataset_practice.csv'
data = pd.read_csv(file_path)

# 데이터의 첫 몇 행과 컬럼 정보 확인
data_head = data.head()
data_columns = data.columns

data_head, data_columns

(                           order_id                       customer_id  \
 0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d   
 1  128e10d95713541c87cd1a2e48201934  a20e8105f23924cd00833fd87daa0831   
 2  0e7e841ddf8f8f2de2bad69267ecfbcf  26c7ac168e1433912a51b924fbd34d34   
 3  bfc39df4f36c3693ff3b63fcbea9e90a  53904ddbea91e1e92b2b3f1d09a7af86   
 4  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef   
 
   order_status order_purchase_timestamp product_category payment_method  \
 0    delivered          2017.10.2 10:56       housewares    credit_card   
 1    delivered          2017.8.15 18:29       housewares    credit_card   
 2    delivered           2017.8.2 18:24       housewares    credit_card   
 3    delivered         2017.10.23 23:26       housewares         boleto   
 4    delivered          2018.7.24 20:41        perfumery         boleto   
 
    installments  item_price_usd  shipping_cost_usd  
 0           1.0          5.6981          

### 2.2 DataFrame 출력하기

- `head()`, `tail()` 함수를 사용해 데이터를 부분적으로 확인
- 함수의 인자로 아무 숫자도 지정하지 않으면 컬럼명을 포함하여 6줄을 출력

💥 **MISSION**

> Dataframe의 `head()`와 `tail()` 사용해보기

In [2]:
print(data.head(), data.tail())

                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d   
1  128e10d95713541c87cd1a2e48201934  a20e8105f23924cd00833fd87daa0831   
2  0e7e841ddf8f8f2de2bad69267ecfbcf  26c7ac168e1433912a51b924fbd34d34   
3  bfc39df4f36c3693ff3b63fcbea9e90a  53904ddbea91e1e92b2b3f1d09a7af86   
4  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef   

  order_status order_purchase_timestamp product_category payment_method  \
0    delivered          2017.10.2 10:56       housewares    credit_card   
1    delivered          2017.8.15 18:29       housewares    credit_card   
2    delivered           2017.8.2 18:24       housewares    credit_card   
3    delivered         2017.10.23 23:26       housewares         boleto   
4    delivered          2018.7.24 20:41        perfumery         boleto   

   installments  item_price_usd  shipping_cost_usd  
0           1.0          5.6981             1.6568  
1   

### 2.3 데이터 타입 확인하기

- `object`: 문자열
- `int`, `float`, `decimal` ..: 숫자형
- `bool`: 불리안

💬 **Chat Prompt**
> 제시한 데이터에서 컬럼들의 타입을 알려줘

🤖 **GPT 출력: Message**

```
제시한 데이터의 각 컬럼에 대한 데이터 타입은 다음과 같습니다:

• order_id: object (문자열)
• customer_id: object (문자열)
• order_status: object (문자열)
• order_purchase_timestamp: object (문자열)
• product_category: object (문자열)
• payment_method: object (문자열)
• installments: float64 (실수형)
• item_price_usd: float64 (실수형)
• shipping_cost_usd: float64 (실수형)

대부분의 컬럼이 문자열로 되어 있으며, installments, item_price_usd, shipping_cost_usd 컬럼은 실수형(float64) 데이터 타입을 가지고 있습니다.
```

🤖 **GPT 출력: Code**

In [3]:
# Checking the data types of each column in the dataset
data_types = data.dtypes
data_types

order_id                     object
customer_id                  object
order_status                 object
order_purchase_timestamp     object
product_category             object
payment_method               object
installments                float64
item_price_usd              float64
shipping_cost_usd           float64
dtype: object

### 2.4 데이터 타입 변경하기

🧑‍💻: 구매 빈도는 정수여야 할 것 같습니다. 데이터의 타입을 변경하도록 해볼까요?

💬 **Chat Prompt**
> installments의 컬럼을 정수형으로 변경해줘

🤖 **GPT 출력: Message**

```
installments 컬럼을 정수형(int64)으로 성공적으로 변환했습니다. 이제 이 컬럼은 더 이상 실수형이 아닌 정수형 데이터를 포함하고 있습니다. 
```

🤖 **GPT 출력: Code**

In [4]:
# Converting the 'installments' column to integer type
data['installments'] = data['installments'].fillna(0).astype(int)

# Verifying the change
data['installments'].dtype

dtype('int64')

📌  **더 알아보기**

- 데이터 타입을 변경하는 것은 `전처리`의 영역에 속함

### 2.5 데이터의 자료형태 확인하기

- 데이터의 자료형태는 `시각화`, `전처리` 그리고 `분석` 시 모두 중요하게 적용되는 개념
- 각 형태에 따라 다른 기법이 사용됨

<p align="center"><img src="https://github.com/sigirace/page-images/blob/main/kang_lectures/gpt_ada/data_type.png?raw=true" width="600" height="300"></p>


| 분류       | 상세 분류  | 설명                                     | **예시**                                              |
| ---------- | ---------- | ---------------------------------------- | ----------------------------------------------------- |
| **범주형** |            | 몇 개의 범주로 나누어진 자료를 의미      |                                                       |
|            | **명목형** | 순서 관계가 없는 자료                    | 성별(남성, 여성), 혈액형(A형, B형, O형, AB형 등)      |
|            | **순서형** | 순서 관계가 존재하는 자료                | 교육 수준(고졸, 대졸, 석사 등), 등급(1등급, 2등급 등) |
| **수치형** |            | 이산형과 연속형으로 이루어진 자료를 의미 |                                                       |
|            | **이산형** | 구분된 값을 가짐                         | 출산 횟수, 방문 횟수                                  |
|            | **연속형** | 연속적인 값을 가짐                       | 신장, 체중, 온도                                      |


💬 **Chat Prompt**
> 제시한 데이터에서 컬럼을 수치형, 범주형으로 구분하여 알려주고 리스트에 저장해줘

🤖 **GPT 출력: Message**

```
• 범주형(Categorical) 컬럼:
	• order_id
	• customer_id
	• order_status
	• order_purchase_timestamp
	• product_category
	• payment_method
• 수치형(Numerical) 컬럼:
	• installments
	• item_price_usd
	• shipping_cost_usd
```	

🤖 **GPT 출력:Code**

In [5]:
# 수치형(Numerical) 컬럼 리스트
numerical_columns = ['installments', 'item_price_usd', 'shipping_cost_usd']

# 범주형(Categorical) 컬럼 리스트
categorical_columns = ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'product_category', 'payment_method']

numerical_columns, categorical_columns

(['installments', 'item_price_usd', 'shipping_cost_usd'],
 ['order_id',
  'customer_id',
  'order_status',
  'order_purchase_timestamp',
  'product_category',
  'payment_method'])

### 2.6 DataFrame 요약 및 통계 확인하기

- 데이터의 내용을 확인했다면 그 이후에 데이터프레임의 요약, 통계정보를 확인함
- `info()` 함수를 통해 `총 데이터의 건수`, `각 컬럼의 데이터 형식` 그리고 `결측치의 건수`를 확인할 수 있음
- 수치형 컬럼이 존재하는 경우 `describe()`함수를 사용하여 수치형 컬럼들의 `n-percentile` 분포도, 평균값, 최대값, 최소값을 확인할 수 있음
- 이러한 과정은 `EDA`에 속함


💬 **Chat Prompt**

```
제시한 데이터의 요약 및 통계정보를 확인해줘
```

🤖 **GPT 출력: Message**

```
제시된 데이터의 요약 및 통계 정보는 다음과 같습니다:

수치형 컬럼의 통계 정보:

 • installments:
 • 총 개수: 997
 • 평균: 3.62
 • 표준 편차: 31.68
 • 최소값: 0
 • 1사분위값: 1
 • 중앙값: 1
 • 3사분위값: 4
 • 최대값: 999
 • item_price_usd:
 • 총 개수: 898
 • 평균: 29.10
 • 표준 편차: 333.61
 • 최소값: 1.805
 • 1사분위값: 13.11
 • 중앙값: 17.10
 • 3사분위값: 20.90
 • 최대값: 9999
 • shipping_cost_usd:
 • 총 개수: 898
 • 평균: 115.49
 • 표준 편차: 3336.87
 • 최소값: -9.595
 • 1사분위값: 2.46
 • 중앙값: 3.06
 • 3사분위값: 5.17
 • 최대값: 99999

범주형 컬럼의 요약 정보:

 • order_id:
 • 총 개수: 997
 • 고유값: 894
 • 최빈값: 52eb8ce94864a3bb1be410a545f9ed4c (6회 발생)
 • customer_id:
 • 총 개수: 997
 • 고유값: 894
 • 최빈값: 4aa0005ef4b8cb5ce874a4a86b36ed05 (6회 발생)
 • order_status:
 • 총 개수: 997
 • 고유값: 4
 • 최빈값: delivered (982회 발생)
 • order_purchase_timestamp:
 • 총 개수: 997
 • 고유값: 893
 • 최빈값: 2017.11.24 23:37 (6회 발생)
 • product_category:
 • 총 개수: 997
 • 고유값: 19
 • 최빈값: health_beauty (278회 발생)
 • payment_method:
 • 총 개수: 997
 • 고유값: 4
 • 최빈값: credit_card (748회 발생) 
이 정보들은 데이터의 전반적인 분포와 특성을 이해하는 데 도움이 됩니다. 
```    

🤖 **GPT 출력: Code**

In [6]:
# 수치형 컬럼에 대한 통계 정보 확인
numerical_summary = data.describe()

# 범주형 컬럼에 대한 요약 정보 확인
categorical_summary = data[categorical_columns].describe()

numerical_summary, categorical_summary

(       installments  item_price_usd  shipping_cost_usd
 count    997.000000      898.000000         898.000000
 mean       3.623872       29.099161         115.493469
 std       31.681427      333.614822        3336.873052
 min        0.000000        1.805000          -9.595000
 25%        1.000000       13.110000           2.464300
 50%        1.000000       17.098100           3.064700
 75%        4.000000       20.898100           5.169425
 max      999.000000     9999.000000       99999.000000,
                                 order_id                       customer_id  \
 count                                997                               997   
 unique                               894                               894   
 top     52eb8ce94864a3bb1be410a545f9ed4c  4aa0005ef4b8cb5ce874a4a86b36ed05   
 freq                                   6                                 6   
 
        order_status order_purchase_timestamp product_category payment_method  
 count           9

💬 **Chat Prompt**
> 범주형 데이터의 고유값에 대해 설명해줘, 단, ID값과 날짜는 제외하고 알려줘

🤖 **GPT 출력: Message**

```
범주형 데이터의 고유값에 대한 설명은 다음과 같습니다(ID값과 날짜는 제외):

order_status (주문 상태):

	• delivered: 982회 발생 (배송 완료)
	• shipped: 12회 발생 (배송 중)
	• invoiced: 2회 발생 (청구서 발행됨)
	• canceled: 1회 발생 (주문 취소됨)

product_category (상품 카테고리):

	• health_beauty: 278회 발생 (건강 및 미용)
	• garden_tools: 219회 발생 (정원 도구)
	• perfumery: 125회 발생 (향수)
	• auto: 91회 발생 (자동차 관련)
	• bed_bath_table: 52회 발생 (침실, 욕실, 테이블 관련)
	• stationery: 41회 발생 (문구류)
	• baby: 40회 발생 (유아용품)
	• toys: 35회 발생 (장난감)
	• watches_gifts: 27회 발생 (시계 및 선물)
	• computers_accessories: 23회 발생 (컴퓨터 및 액세서리)
	• telephony: 19회 발생 (전화기 관련)
	• electronics: 13회 발생 (전자기기)
	• office_furniture: 9회 발생 (사무용 가구)
	• cool_stuff: 6회 발생 (멋진 물건)
	• pet_shop: 5회 발생 (애완동물 용품)
	• furniture_decor: 5회 발생 (가구 및 장식)
	• housewares: 4회 발생 (가정용품)
	• construction_tools_construction: 4회 발생 (건설 도구)
	• air_conditioning: 1회 발생 (에어컨)

payment_method (결제 수단):

	• credit_card: 748회 발생 (신용카드)
	• boleto: 202회 발생 (브라질의 지불 수단)
	• voucher: 35회 발생 (바우처)
	• debit_card: 12회 발생 (직불카드)

이 고유값들은 각 범주형 컬럼에서 나타나는 값들의 빈도와 분포를 보여줍니다.
```    

📌 **더 알아보기**

- 데이터 `요약`, `통계정보`를 통해 `이상치` 및 `결측치`에 대한 처리를 어떻게 해야할지 대략적인 감을 잡을 수 있음

***

## 3. 조건에 맞는 데이터 탐색

### 3.1 단일 조건으로 데이터 탐색

💬 **Chat Prompt**
> 제시한 데이터에서 제품 카테고리가 장난감인 것들만 탐색해줘

🤖 **GPT 출력: Code**

In [7]:
# Filtering the dataset for rows where the product_category is 'toys'
toys_data = data[data['product_category'] == 'toys']

# Displaying the filtered data
print(toys_data.head())

                             order_id                       customer_id  \
424  432aaf21d85167c2c86ec9448c4e42cc  3df704f53d3f1d4818840b34ec672a9f   
425  4e2160ff7a61b2bf4fbd2e527ea924d3  ea36ec29b56eded534644f21b9561efc   
426  588e9a3844482484a31e604c2767b82f  c6d04a9495cc4d8e22a4276131aac50e   
427  0d2d1445891e7aba669fa2069d695601  739ee2d2d5960609ad780937fd9fa282   
428  ce0e053019fe2441df8363b9bf4208a7  eb0e5e03030a71a038d3e71bdbe82d86   

    order_status order_purchase_timestamp product_category payment_method  \
424    delivered           2018.3.1 14:14             toys    credit_card   
425    delivered           2018.2.9 13:48             toys    credit_card   
426    delivered          2018.3.24 21:50             toys         boleto   
427    delivered          2017.10.9 19:54             toys         boleto   
428    delivered          2017.12.4 20:15             toys    credit_card   

     installments  item_price_usd  shipping_cost_usd  
424             1          7.26

### 3.2 다중 조건으로 데이터 탐색

💬 **Chat Prompt**
> 제시한 데이터에서 product_category가 장난감이고 installments이 평균 이상인 것들만 탐색해줘

🤖 **GPT 출력: Code**

In [8]:
# Calculating the mean of 'installments'
installments_mean = data['installments'].mean()

# Filtering the dataset for rows where the product_category is 'toys' and installments are above the mean
toys_above_mean_installments = data[(data['product_category'] == 'toys') & (data['installments'] > installments_mean)]

print(toys_above_mean_installments)

                             order_id                       customer_id  \
445  fa5927f07ada4f44128f6d9fab3b70f6  8af801d95c9bc9bd7cfa7845826e4b72   
452  d9971834a50b8fc323aa7f527978169d  4899884819536b44b5b533849b3683ce   
453  d9971834a50b8fc323aa7f527978169d  4899884819536b44b5b533849b3683ce   
455  7c74b6a47ffad9deb24bd2a1f0b0acc5  95e4216612b16855852e2b9efa6174d2   

    order_status order_purchase_timestamp product_category payment_method  \
445    delivered           2018.2.2 10:18             toys    credit_card   
452    delivered           2017.9.27 0:07             toys    credit_card   
453    delivered           2017.9.27 0:07             toys    credit_card   
455    delivered          2017.12.4 17:22             toys    credit_card   

     installments  item_price_usd  shipping_cost_usd  
445             5          7.2675             3.4048  
452            10          7.2675             3.0609  
453            10          7.2675             3.0609  
455             5 

## 4. 데이터 요약

데이터를 요약하여 원하는 정보를 얻는 것은 데이터가 지닌 값의 특징을 알게 해줍니다. 이와 비슷한 것을 2장에서 수행해보았는데, 이번 장에서는 세부적으로 데이터를 요약하여 집계하는 방법을 알아보겠습니다.

### 4.1 그룹화 집계

👀 **Definition**
> 그룹화는 하나 이상의 데이터를 조건에 따라 여러개 그룹으로 묶는 것

- groupby() 함수를 사용함

📌 **groupby**

> DataFrame.groupby(by=None, axis=0, sort=False, dropna=True).FUN()

- by: 그룹을 결정하는 데 사용
- axis: 행(0)과 열(1) 지정c
- sort: 집계된 내용을 정렬할지 여부
- dropna: True이면 결측값이 행/열과 함께 삭제, False이면 결측값도 그룹의 키로 처리
- FUN: 집계함수

🔥 **집계함수**

- count(): 값의 개수
- sum(): 값들의 합
- std(): 표준편차
- var(): 분산
- min(): 최솟값
- max(): 최대값
- mean(): 평균값
- median(): 중앙값

🧑‍💻: product_category 별로 다양한 집계를 수행해 봅니다.

💬 **Chat Prompt**

> product_category 값을 기준으로 집계 함수 count를 수행해줘

🤖 **GPT 출력: Message**

```
product_category 값을 기준으로 각 카테고리의 주문 수를 집계한 결과는 다음과 같습니다:

	• health_beauty: 278
	• garden_tools: 219
	• perfumery: 125
	• auto: 91
	• bed_bath_table: 52
	• stationery: 41
	• baby: 40
	• toys: 35
	• watches_gifts: 27
	• computers_accessories: 23
	• telephony: 19
	• electronics: 13
	• office_furniture: 9
	• cool_stuff: 6
	• pet_shop: 5
	• furniture_decor: 5
	• housewares: 4
	• construction_tools_construction: 4
	• air_conditioning: 1

이 결과는 각 카테고리에 속한 주문의 빈도를 보여줍니다.
```

🤖 **GPT 출력: Code**

In [9]:
# product_category를 기준으로 각 카테고리의 주문 수를 집계
category_count = data['product_category'].value_counts()

category_count

health_beauty                      278
garden_tools                       219
perfumery                          125
auto                                91
bed_bath_table                      52
stationery                          41
baby                                40
toys                                35
watches_gifts                       27
computers_accessories               23
telephony                           19
electronics                         13
office_furniture                     9
cool_stuff                           6
pet_shop                             5
furniture_decor                      5
housewares                           4
construction_tools_construction      4
air_conditioning                     1
Name: product_category, dtype: int64

💬 **Chat Prompt**
> product_category 값을 기준으로 installments의 평균을 구해줘 (집계함수 mean 적용)

🤖 **GPT 출력: Message**

```
product_category 값을 기준으로 installments의 평균을 계산한 결과는 다음과 같습니다:

	• air_conditioning: 0.00
	• auto: 2.09
	• baby: 3.23
	• bed_bath_table: 1.75
	• computers_accessories: 2.13
	• construction_tools_construction: 10.00
	• cool_stuff: 3.67
	• electronics: 2.15
	• furniture_decor: 0.60
	• garden_tools: 2.71
	• health_beauty: 6.60
	• housewares: 1.25
	• office_furniture: 2.11
	• perfumery: 2.78
	• pet_shop: 1.40
	• stationery: 1.10
	• telephony: 1.74
	• toys: 1.89
	• watches_gifts: 4.11

이 값들은 각 상품 카테고리별 할부 횟수의 평균을 나타냅니다. 
```

🤖 **GPT 출력: Code**

In [10]:
# product_category를 기준으로 installments의 평균을 계산
installments_mean_by_category = data.groupby('product_category')['installments'].mean()

installments_mean_by_category

product_category
air_conditioning                    0.000000
auto                                2.087912
baby                                3.225000
bed_bath_table                      1.750000
computers_accessories               2.130435
construction_tools_construction    10.000000
cool_stuff                          3.666667
electronics                         2.153846
furniture_decor                     0.600000
garden_tools                        2.712329
health_beauty                       6.597122
housewares                          1.250000
office_furniture                    2.111111
perfumery                           2.776000
pet_shop                            1.400000
stationery                          1.097561
telephony                           1.736842
toys                                1.885714
watches_gifts                       4.111111
Name: installments, dtype: float64

💬 **Chat Prompt**
> 집계 함수로 구한 product_category 값을 기준으로 installments의 평균에 대해 결과를 해석해서 설명해줘

🤖 **GPT 출력: Message**

```
각 product_category(상품 카테고리)별로 installments(할부 횟수)의 평균을 분석한 결과는 다음과 같습니다:

	1. 높은 할부 횟수:
	• construction_tools_construction (10.00): 이 카테고리에서는 평균 10회의 할부가 적용되었습니다. 이는 고가의 상품이 포함될 가능성이 높으며, 구매자들이 비용을 분할하여 지불하는 경향이 강하다는 것을 나타냅니다.
	• health_beauty (6.60): 건강 및 미용 제품도 비교적 높은 할부 횟수를 보입니다. 이는 고객들이 이 카테고리의 상품을 구매할 때 할부를 자주 선택한다는 것을 의미합니다.
	2. 중간 할부 횟수:
	• watches_gifts (4.11), cool_stuff (3.67), baby (3.23): 이 카테고리들은 중간 수준의 할부 횟수를 가지고 있으며, 이는 구매자들이 이러한 제품을 구매할 때 어느 정도의 분할 지불을 선호한다는 것을 보여줍니다.
	• perfumery (2.78), auto (2.09): 이 카테고리들도 중간 정도의 할부 횟수를 보입니다. 특히 향수(perfumery)와 자동차 관련 상품(auto)도 일정 수준의 할부를 통해 구매된다는 것을 알 수 있습니다.
	3. 낮은 할부 횟수:
	• stationery (1.10), housewares (1.25), telephony (1.74): 문구류, 가정용품, 전화기 관련 제품들은 평균적으로 낮은 할부 횟수를 보입니다. 이는 이들 제품이 비교적 저렴하거나, 구매자들이 할부 대신 일시불로 지불하는 경우가 많다는 것을 시사합니다.
	• air_conditioning (0.00): 에어컨 관련 카테고리의 경우, 할부가 전혀 선택되지 않았습니다. 이는 이 데이터셋에서 해당 제품이 매우 적거나, 일시불로 지불된다는 것을 의미할 수 있습니다.

결론:

이 결과는 카테고리별로 할부 지불 방식이 다르며, 고가의 상품일수록 할부 횟수가 높아지는 경향이 있음을 보여줍니다. 반면, 저렴하거나 상대적으로 일상적인 제품들은 대부분 낮은 할부 횟수로 구매되거나 일시불로 처리됩니다. 이는 고객의 구매 패턴과 선호도를 파악하는 데 유용한 정보입니다.
```

***

## 5. 데이터 정렬하기

### 5.1 컬럼의 값에 대해 데이터 정렬하기

💬 **Chat Prompt**
> order_purchase_timestamp을 기준으로 오름차순 정렬을 수행해줘

🤖 **GPT 출력: Message**

```
order_purchase_timestamp를 기준으로 오름차순 정렬을 수행한 결과, 가장 오래된 주문부터 순차적으로 정렬되었습니다. 상위 5개의 데이터는 다음과 같습니다:

	1. 2017.1.23 18:29 - furniture_decor 카테고리, boleto 결제, 할부 없음.
	2. 2017.1.30 10:47 - auto 카테고리, credit_card 결제, 할부 없음.
	3. 2017.1.31 17:40 - auto 카테고리, credit_card 결제, 1회 할부.
	4. 2017.10.1 20:04 - health_beauty 카테고리, credit_card 결제, 1회 할부.
	5. 2017.10.1 09:15 - auto 카테고리, boleto 결제, 1회 할부.

이 데이터를 통해 시간 순서대로 주문 내역을 확인할 수 있습니다. 
```

🤖 **GPT 출력: Code**

In [11]:
# order_purchase_timestamp을 기준으로 오름차순 정렬 수행
data_sorted_by_timestamp = data.sort_values(by='order_purchase_timestamp', ascending=True)

# 정렬된 데이터 확인 (상위 5개)
print(data_sorted_by_timestamp.head())

                             order_id                       customer_id  \
248  76c6e866289321a7c93b82b54852dc33  f54a9f0e6b351c431402b8461ea51999   
189  9559e0b00c67d159a266152428f85615  c3498e41d1549d56c4cbde7cbfdabeb3   
244  35aa6b03b34d8d0a5c1eaae2bb5fcf76  18f5e4ab94b6b5fdcf32dade57defe50   
511  80dabd6ee5b0e0d7d5672d511ca8cc7e  fbea4ed949b70f597425d14164f82851   
247  3389e2333066b728a245423a73f3f82c  45c155ac404d868fd8f1d07e8cd916c3   

    order_status order_purchase_timestamp product_category payment_method  \
248    delivered          2017.1.23 18:29  furniture_decor         boleto   
189    delivered          2017.1.30 10:47             auto    credit_card   
244    delivered          2017.1.31 17:40             auto    credit_card   
511    delivered          2017.10.1 20:04    health_beauty    credit_card   
247    delivered           2017.10.1 9:15             auto         boleto   

     installments  item_price_usd  shipping_cost_usd  
248             0          3.78

📌 **더 알아보기**

- 정렬을 수행한 후에는 인덱스가 섞인 상태
- 인덱스가 섞이면 추후 분석과정에서 오류가 발생할 수 있으므로 인덱스 또한 정렬이 필요
- 이때, 값은 건들이지 않고 인덱스만을 정렬함

💬 **Chat Prompt**
> 인덱스를 정렬해주고, 과거의 인덱스는 버려줘

🤖 **GPT 출력: Message**

```
이제 데이터는 order_purchase_timestamp를 기준으로 오름차순 정렬되었으며, 인덱스도 새로운 순서에 맞게 재설정되었습니다. 
과거의 인덱스는 제거되었으며, 현재 데이터는 정렬된 순서에 맞는 새로운 인덱스를 가지고 있습니다.
```

🤖 **GPT 출력: Code**

In [12]:
# 인덱스를 정렬된 데이터의 순서에 맞게 재설정하고, 이전 인덱스는 제거
data_sorted_by_timestamp.reset_index(drop=True, inplace=True)

# 재설정된 인덱스를 가진 데이터 확인 (상위 5개)
print(data_sorted_by_timestamp.head())

                           order_id                       customer_id  \
0  76c6e866289321a7c93b82b54852dc33  f54a9f0e6b351c431402b8461ea51999   
1  9559e0b00c67d159a266152428f85615  c3498e41d1549d56c4cbde7cbfdabeb3   
2  35aa6b03b34d8d0a5c1eaae2bb5fcf76  18f5e4ab94b6b5fdcf32dade57defe50   
3  80dabd6ee5b0e0d7d5672d511ca8cc7e  fbea4ed949b70f597425d14164f82851   
4  3389e2333066b728a245423a73f3f82c  45c155ac404d868fd8f1d07e8cd916c3   

  order_status order_purchase_timestamp product_category payment_method  \
0    delivered          2017.1.23 18:29  furniture_decor         boleto   
1    delivered          2017.1.30 10:47             auto    credit_card   
2    delivered          2017.1.31 17:40             auto    credit_card   
3    delivered          2017.10.1 20:04    health_beauty    credit_card   
4    delivered           2017.10.1 9:15             auto         boleto   

   installments  item_price_usd  shipping_cost_usd  
0             0          3.7810             3.0495  
1   

***

## 6. DataFrame에 함수 적용하기

Apply와 Map 함수를 사용하여 데이터의 행 또는 열에 자유롭게 함수를 적용하고 값을 변경할 수 있습니다.

- apply/ map 둘 다 동일한 기능 수행
- 데이터프레임에 행 또는 열 방향으로 지정한 함수 실행

🔥 **꿀팁**
- lambda는 apply를 시작할 때 "lambda 뒤에 오는 변수를 가지고 수행할거야!"라는 뜻
- 이 변수는 하나의 컬럼일 수도 있고 여러 컬럼일 수 도 있으며 다양한 처리를 수행할 수 있음
- 대상이 여러 컬럼일 경우 axis=1를 꼭 명시해야함

### 6.1 하나의 컬럼에 대한 수행

💬 **Chat Prompt**


> 데이터프레임에 installment_divide라는 컬럼을 추가해줘 <br>
> installment_divide라는 installment 컬럼을 12로 나눈 값이야, apply를 적용해서 수행해줘

🤖 **GPT 출력: Message**

```
데이터프레임에 installment_divide라는 컬럼이 추가되었으며, installments 컬럼의 값을 12로 나눈 결과가 해당 컬럼에 저장되었습니다.
예를 들어, installments 값이 1인 경우 installment_divide 값은 0.0833입니다.
```

🤖 **GPT 출력: Code**

In [13]:
# installment_divide라는 컬럼을 추가하여 installments 컬럼의 값을 12로 나눈 값을 할당
data_sorted_by_timestamp['installment_divide'] = data_sorted_by_timestamp['installments'].apply(lambda x: x / 12)

# 추가된 컬럼 확인 (상위 5개)
print(data_sorted_by_timestamp[['installments', 'installment_divide']].head())

   installments  installment_divide
0             0            0.000000
1             0            0.000000
2             1            0.083333
3             1            0.083333
4             1            0.083333


### 6.2 여러 컬럼에 대한 수행

💬 **Chat Prompt**
> 데이터 프레임에 monthly_price 컬럼을 만들어줘 <br>
> installment_divide 컬럼과 item_price_usd를 곱한 값이야, apply를 적용해서 수행해줘

🤖 **GPT 출력: Message**

```
데이터프레임에 monthly_price라는 컬럼이 추가되었습니다. 이 컬럼은 installment_divide와 item_price_usd를 곱한 값으로 계산되었습니다. 예를 들어, installments 값이 1이고 item_price_usd가 9.4981인 경우 monthly_price 값은 0.791508입니다.

이제 각 상품의 할부 금액에 해당하는 월별 가격을 확인할 수 있습니다.
```

🤖 **GPT 출력: Code**

In [14]:
# monthly_price 컬럼을 추가하여 installment_divide와 item_price_usd를 곱한 값을 할당
data_sorted_by_timestamp['monthly_price'] = data_sorted_by_timestamp.apply(
    lambda row: row['installment_divide'] * row['item_price_usd'], axis=1
)

# 추가된 컬럼 확인 (상위 5개)
print(data_sorted_by_timestamp[['installment_divide', 'item_price_usd', 'monthly_price']].head())

   installment_divide  item_price_usd  monthly_price
0            0.000000          3.7810       0.000000
1            0.000000         28.1010       0.000000
2            0.083333          9.4981       0.791508
3            0.083333         17.0981       1.424842
4            0.083333             NaN            NaN


***

## 7. 데이터 저장

💬 **Chat Prompt**


> 현재까지 만들어진 데이터를 다운로드 받을 수 있는 링크를 만들어줘


🤖 **GPT 출력: Message**

```
데이터를 다운로드할 수 있는 링크를 생성했습니다. 아래 링크를 클릭하여 데이터를 다운로드할 수 있습니다:

다운로드 링크 ￼
```